---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-money-web-deployment
  labels:
    app: multi-money
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-money
  template:
    metadata:
      labels:
        app: multi-money
    spec:
      containers:
        - name: multi-money-web-container
          image: multi-money-web
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: GOOGLE_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-oauth-client-id
                  key: GOOGLE_OAUTH_CLIENT_ID
            - name: GOOGLE_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-oauth-client-secret
                  key: GOOGLE_OAUTH_CLIENT_SECRET
