---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-money-web-deployment
  labels:
    app: multi-money
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-money
  template:
    metadata:
      labels:
        app: multi-money
    spec:
      volumes:
        - name: config
          secret:
            secretName: config
      containers:
        - name: multi-money-web-container
          image: multi-money-web
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            - name: CONFIG
              value: /etc/config.edn
          volumeMounts:
            - name: config
              readOnly: true
              mountPath: /etc/config.edn
