---
apiVersion: batch/v1
kind: Job
metadata:
  name: sql-migration
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: sql-migrate
          image: multi-money-migrate
          envFrom:
            - secretRef:
                name: secret-config
  backoffLimit: 2
