---
apiVersion: v1
kind: Service
metadata:
  name: multi-money-web-service
  namespace: staging
spec:
  selector:
    app: multi-money
  ports:
    - port: 80
      targetPort: 3204
  type: LoadBalancer
