---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-data
  labels:
    type: local # TODO: this will surely change for cloud deployment
    app: multi-money-sql
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/sql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data-claim
  labels:
    app: multi-money-sql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-money-sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-money-sql
  template:
    metadata:
      labels:
        app: multi-money-sql
    spec:
      containers:
        - name: multi-money-sql
          image: postgres:16
          ports:
            - containerPort: 5432
          env: # TODO: get these from secrets instead
            - name: POSTGRES_DB
              value: multi_money
            - name: POSTGRES_USER
              value: app_user
            - name: POSTGRES_PASSWORD
              value: please01
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: sql-data
      volumes:
        - name: sql-data
          persistentVolumeClaim:
            claimName: sql-data-claim
---
apiVersion: v1
kind: Service
metadata:
  name: multi-money-sql
  labels:
    app: multi-money-sql
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: multi-money-sql
