---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-money-web-deployment
  namespace: staging
  labels:
    app: multi-money
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multi-money
  template:
    metadata:
      labels:
        app: multi-money
    spec:
      containers:
        - name: multi-money-web-container
          image: dgknght/multi-money:pr-4
          ports:
            - containerPort: 3204
