---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - namespace.yml
namespace: production
images:
  - name: multi-money
    newName: registry.hub.docker.com/dgknght/multi-money
    newTag: latest
