---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - namespace.yml
namespace: production
images:
  - name: multi-money-web
    newName: registry.hub.docker.com/dgknght/multi-money-web
    newTag: pr-8-61ff70a
  - name: multi-money-migrate
    newName: registry.hub.docker.com/dgknght/multi-money-migrate
    newTag: pr-8-61ff70a
