---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - namespace.yml
namespace: staging
images:
  - name: multi-money
    newName: dgknght/multi-money
    newTag: pr-4
